apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: amazon/aws-efs-csi-driver
    newTag: v1.5.5
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.9.0-eks-1-27-latest
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.7.0-eks-1-27-latest
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v3.4.0-eks-1-27-latest
